-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid gen_random_uuid(),
    role text NOT NULL CHECK (role IN ('patient', 'tuteur/parent', 'visiteur', 'medecin')),
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    gender text CHECK(gender IN('M', 'F')),
    email text,
    password_hash text NOT NULL,
    city character varying(80),
    country character varying(80) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    last_login timestamp with time zone DEFAULT now(),
    PRIMARY KEY (user_id)
    -- UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    patient_id uuid gen_random_uuid() NOT NULL,
	user_id UUID UNIQUE NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    genotype text CHECK (genotype IN ('SS','AS','SC', 'Sβ0', 'Sβ+')),
    birth_date date NOT NULL,
    close_contact character varying(80),
    device_id uuid,
    PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS public.parents
(
	
    parent_id uuid REFERENCES users(user_id) ON DELETE CASCADE,
    -- user_id uuid UNIQUE NOT NULL REFERENCES users(user_id),
    patient_id uuid REFERENCES patients(patient_id),
    birth_date date,
    PRIMARY KEY (parent_id)
);
CREATE INDEX idx_parents_ts ON parents (patient_id, parent_id, ts DESC)

CREATE TABLE IF NOT EXISTS public.visitor
(
    visitor_id uuid REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (visitor_id)
);

CREATE TABLE IF NOT EXISTS public.clinicians
(
    clinician_id uuid REFERENCES users(user_id) ON DELETE CASCADE,
    --user_id uuid,
    patient_id uuid REFERENCES patients(patient_id) ON DELETE CASCADE,
    speciality character varying(80),
    service_location character varying(80),
    PRIMARY KEY (clinician_id)
);
CREATE INDEX idx_clinicians_patient_ts ON clinicians (clinician_id, patient_id, ts DESC);

CREATE TABLE IF NOT EXISTS public.location_patient
(
    location_id uuid gen_random_uuid(),
    patient_id uuid REFERENCES patients(patient_id) ON DELETE CASCADE,
    latitude double precision,
    longitude double precision,
    ts timestamp with time zone,
    PRIMARY KEY (location_id)
);
CREATE INDEX idx_loc_patient_ts ON location_patient(patient_id, ts DESC);

CREATE TABLE IF NOT EXISTS public.measurements
(
    measure_id bigserial,
    patient_id uuid NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
    tz_timestamp timestamp with time zone NOT NULL,
    device_id uuid gen_random_uuid NOT NULL,
    freq_card smallint,
    freq_resp smallint,
    spo2_pct numeric(5,2),
    temp_corp numeric(4,2),
    temp_abiante numeric(4,2),
    pct_hydratation numeric(5,2),
    activity INT,
	heat_index NUMERIC(4,2),
    quality_flag text,
    PRIMARY KEY (device_id)
);
CREATE INDEX idx_mesure_patient_ts ON measurements (patient_id, tz_timestamp DESC);

-- 1) Reference table for measurement quality codes
CREATE TABLE IF NOT EXISTS measurement_quality (
  code TEXT PRIMARY KEY,           -- machine-readable (snake_case)
  label TEXT NOT NULL,             -- human label
  severity SMALLINT NOT NULL,      -- 0=ok, 1=info, 2=warning, 3=error
  description TEXT,
  deprecated_at TIMESTAMPTZ
);

-- Seed standard codes (idempotent upsert)
INSERT INTO measurement_quality (code, label, severity, description) VALUES
  ('ok',            'OK / Valid',                0, 'Measurement validated / usable',                        NULL),
  ('motion',        'Motion artifact',           2, 'Detected motion likely corrupts the signal',            NULL),
  ('low_signal',    'Low signal',                2, 'Weak sensor signal (e.g., poor contact)',               NULL),
  ('low_perfusion', 'Low perfusion',             2, 'Common cause of SpO2 artifacts',                        NULL),
  ('sensor_drop',   'Sensor drop',               3, 'Sensor disconnected / slippage',                        NULL),
  ('signal_loss',   'Signal loss',               3, 'Loss of data (RF disconnect, timeout)',                 NULL),
  ('noise',         'Electrical/EMI noise',      2, 'Electrical interference / noise in reading',            NULL),
  ('out_of_range',  'Out of physiological range',3, 'Value out of plausible physiological range',            NULL),
  ('calibrating',   'Calibrating',               1, 'Device is calibrating, values not reliable',            NULL),
  ('checksum_fail', 'Checksum failed',           3, 'Payload integrity check failed',                        NULL),
  ('device_error',  'Device error',              3, 'Hardware/software device error',                        NULL),
  ('user_removed',  'User removed device',       1, 'Temporary removal by user (e.g., shower, sports)',      NULL)
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  severity = EXCLUDED.severity,
  description = EXCLUDED.description,
  deprecated_at = EXCLUDED.deprecated_at;

-- Ensure measurements.quality_flag exists (legacy) and enforce format
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='measurements' AND column_name='quality_flag'
  ) THEN
    ALTER TABLE measurements ADD COLUMN quality_flag TEXT;
  END IF;
END$$;

-- Optional helper view to enrich measurements with quality metadata
CREATE OR REPLACE VIEW v_measurements_enriched AS
SELECT
  m.*,
  q.label  AS quality_label,
  q.severity AS quality_severity,
  q.description AS quality_description
FROM measurements m
LEFT JOIN measurement_quality q ON q.code = m.quality_flag;

--------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.alerts
(
    alert_id bigserial,
    patient_id uuid NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
    alert_type text NOT NULL,
    severity text CHECK (severity IN ('low','medium','hight', 'criticial')),
    message text,
    created_at time with time zone DEFAULT now(),
    PRIMARY KEY (alert_id)
);
CREATE INDEX idx_alerte_patient_date ON alerte (patient_id, created_at DESC);

------
CREATE TABLE IF NOT EXISTS public.alert_statut_logs
(
    alert_id bigint REFERENCES alerts(alert_id) ON DELETE CASCADE,
    statut text CHECK (status IN ('created', 'seen', 'resolved')) NOT NULL,
    changed_at time with time zone DEFAULT now(),
    changer_by uuid REFERENCES users(user_id),
    "(alert_id, changed_at)" uuid,
    PRIMARY KEY ("(alert_id, changed_at)")
);

------
CREATE TABLE IF NOT EXISTS public.treatments 
(	
	traitment_id uuid gen_random_uuid(),
	patient_id uuid NOT NULL REFERENCES patient(patient_id) ON DELETE CASCADE,
	drug_name TEXT NOT NULL,
	treatment_start DATE,
	treatment_end DATE,
	prescriber_id BIGINT REFERENCES clinicians (clinician_id),
	PRIMARY KEY (traitment_id)
);
CREATE INDEX idx_traitment_patient_date ON treatments(patient_id, treatment_start DESC);


CREATE TABLE IF NOT EXISTS public.session
(
    session_id uuid gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    start_at time with time zone NOT NULL DEFAULT now(),
    end_at time with time zone,
    ip inet,
    PRIMARY KEY (session_id)
);
CREATE INDEX idx_session_user_ts ON session_connexion(user_id, start_at DESC);

CREATE TABLE IF NOT EXISTS public.logs_iot
(
	log_id uuid gen_random_uuid(),
	device_id uuid NOT NULL REFERENCES measurements(device_id),
	patient_id uuid REFERENCES patients(patient_id),
	status TEXT CHECK (status IN ('connected', 'low_battery', 'offline')),
	timestamp time with time zone DEFAULT now(),
	PRIMARY KEY (log_id)
);
CREATE INDEX idx_logs_iot ON logs_iot (patient_id, device_id DESC);


END;
